# for preview
name: seata website deploy on my github

on:
  push:
    branches:
      - deploy

permissions:
  contents: write

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 19.5.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.5.x
      - name: Build
        run: |
          npm install && npm run build && mkdir -p deploy-dist && cp -R build/* deploy-dist/ && mv build .htaccess .asf.yaml deploy-dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./deploy-dist
